apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: LoadBalancer
  selector:
    app: vproapp
  ports:
    - name: http
      port: 80
      targetPort: vproapp-port
      protocol: TCP

